name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        path: aoppa
